# Generated by Django 4.2.1 on 2023-06-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('regnr', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('notering', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('service_date', models.DateTimeField()),
                ('regnr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booker.customermodel')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booker.servicetypemodel')),
            ],
        ),
    ]
