# Generated by Django 4.2.1 on 2023-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='status',
            field=models.CharField(choices=[('Bokad', 'Bokad'), ('Utförd', 'Utförd'), ('Avbokad', 'Avbokad')], default='Bokad', max_length=20),
            preserve_default=False,
        ),
    ]
