# Generated by Django 4.2.1 on 2023-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_servicemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypemodel',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
