# Generated by Django 4.2.1 on 2023-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_servicetypemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='status',
            field=models.CharField(choices=[('Bokad', 'Bokad'), ('Utförd', 'Utförd'), ('Avbokad', 'Avbokad')], default='Bokad', max_length=20),
        ),
    ]
