# Generated by Django 4.2.1 on 2023-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_alter_servicemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='way_of_booking',
            field=models.CharField(choices=[('', ''), ('Inloggad', 'Inloggad'), ('Utloggad', 'Utloggad'), ('Telefon', 'Telefon'), ('Email', 'Email'), ('Verkstad', 'Verkstad')], default='', max_length=20),
        ),
    ]
