# Generated by Django 4.2.1 on 2023-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_servicetypemodel_sort_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='service_protocol',
            field=models.FileField(default='', upload_to='media/protocols/'),
            preserve_default=False,
        ),
    ]
