# Generated by Django 4.2.1 on 2023-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0008_servicemodel_service_protocol_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypemodel',
            name='service_price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=20),
        ),
    ]
