# Generated by Django 4.2.1 on 2023-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0009_alter_servicetypemodel_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inkommen', models.DateTimeField(auto_now=True)),
                ('namn', models.CharField(max_length=255)),
                ('regnr', models.CharField(max_length=255)),
                ('telnr', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('meddelande', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, default='')),
                ('klart', models.CharField(choices=[('Oläst', 'Oläst'), ('I behandling', 'I behandling'), ('Väntar på kund', 'Väntar på kund'), ('Klart', 'Klart')], default='Oläst', max_length=15)),
            ],
        ),
    ]
