# Generated by Django 4.2.1 on 2023-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0011_paymentsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Kundkontakter', 'verbose_name_plural': 'Kundkontakter'},
        ),
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name': 'Kunder', 'verbose_name_plural': 'Kunder'},
        ),
        migrations.AlterModelOptions(
            name='paymentsmodel',
            options={'verbose_name': 'Betalningar', 'verbose_name_plural': 'Betalningar'},
        ),
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'verbose_name': 'Bokningar', 'verbose_name_plural': 'Bokningar'},
        ),
        migrations.AlterModelOptions(
            name='servicetypemodel',
            options={'verbose_name': 'Våra servicar', 'verbose_name_plural': 'Våra servicar'},
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='orders',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='klart',
            field=models.CharField(choices=[('Oläst', 'Oläst'), ('I behandling', 'I behandling'), ('Väntar på kund', 'Väntar på kund'), ('Beställt delar', 'Beställt delar'), ('Klart', 'Klart')], default='Oläst', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='status',
            field=models.CharField(choices=[('Bokad', 'Bokad'), ('Beställning pågår', 'Beställning pågår'), ('Utförd', 'Utförd'), ('Avbokad', 'Avbokad')], default='Bokad', max_length=20),
        ),
    ]
