# Generated by Django 4.1.7 on 2023-03-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardOffert',
            fields=[
                ('offert', models.AutoField(primary_key=True, serialize=False)),
                ('regnr', models.CharField(max_length=255)),
                ('momstotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totalpris', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('giltigt_tom', models.DateField()),
            ],
            options={
                'verbose_name': 'Offerter',
                'verbose_name_plural': 'Offerter',
            },
        ),
        migrations.CreateModel(
            name='OffertPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt', models.CharField(max_length=255)),
                ('pris', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('moms', models.DecimalField(decimal_places=2, default=0.25, max_digits=6)),
                ('totalpris', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('offert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerter.standardoffert')),
            ],
        ),
    ]
