# Generated by Django 4.1.7 on 2023-03-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardoffert',
            name='pris_ex_moms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
