# Generated by Django 4.1 on 2023-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerter', '0003_alter_standardoffert_momstotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardoffert',
            name='action',
            field=models.CharField(default='', max_length=255),
        ),
    ]
