# Generated by Django 4.1 on 2023-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerter', '0004_standardoffert_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardoffert',
            name='action',
        ),
        migrations.AddField(
            model_name='standardoffert',
            name='noteringar',
            field=models.TextField(default=''),
        ),
    ]
